[package]
name = "ip-tools"
version = "0.1.0"
edition = "2021"
description = "IP Tools"
authors = ["Mystic"]
repository = "https://github.com/pplmx/ip-tools"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~3.2.17", features = ["cargo"] }
get_if_addrs = "0.5.3"
local-ip-address = "~0.4.6"

[profile.test]
opt-level = 1

[profile.bench]
lto = true
codegen-units = 1
