#!/bin/sh
[ "$HUSKY" = "0" ] && exit 0

echo "Running pre-commit checks..."

cargo fmt --all --check
if [ $? -ne 0 ]; then
    echo "Code is not formatted. Run: cargo fmt --all"
    exit 1
fi

cargo clippy --all-targets --all-features --workspace -- -D warnings -W clippy::pedantic -W clippy::nursery
if [ $? -ne 0 ]; then
    echo "Clippy checks failed!"
    exit 1
fi

echo "Pre-commit checks passed"
